# Generated by Django 4.2.4 on 2024-02-26 15:21

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', markdownx.models.MarkdownxField()),
                ('isPublic', models.BooleanField(default=False)),
            ],
        ),
    ]
